### ISSUE TITLE
Improvement - Add command line option to convert .csv in Excel table 

### ISSUE THREAD

**Issue by bovirus** [nmolinos/csv2excel#18] opened 2024-02-06 13:32 UTC
@nmolinos 

Thanks to add in 2.1.0 version "-r" to the command line for Excel column autosize.

Could be possible to add other command line option to convert csv in Execl file as table?

In this way starting from a csv file with column names in first line via command line you can convert in EXecl table with autosize columns.

Thanks.

**Comment by nmolinos** [comment] 2024-02-10 18:16
Duplicate of #17

**Closed by nmolinos** 2024-02-10 18:16 UTC

**Comment by bovirus** [comment] 2024-02-16 13:10
@nmolinos 

Please re-open this ticket.

Please take care that I didn't consider this my request as a duplicate request.
For me is differnet to convert csv in excel file and convert csv in excel table file.
The fiel have same extension (x.ls/.xlsx) but different content/layout.

Currently your tool convert csv in excel (not excel table) file.

My request is add an option to convert csv in Excel table file with first line of CSV file as header/control field of Excel table file.

Thanks.

**Comment by nmolinos** [comment] 2024-02-16 16:00
Isn't this still a duplicate of issue #17?  Feel free to edit #17 so
references of xlsx say Excel, if you'd like.  The new feature would work
for both formats anyway, unless there is a technical limitation that would
prevent that from happening (which I doubt is the case).

Thanks.

**Comment by bovirus** [comment] 2024-02-17 14:21
@nmolinos

The standard command line convert a csv in a  simple Excel file (not Excel table file).
Which the option to convert a csv in Excel file with table inside (that it's differnt then xls not table file)?

**Comment by nmolinos** [comment] 2024-02-17 16:19
Command line option TBD based on work done in issue #17.
